/**
 * Write the desktop Google credentials into the packaged app.
 *
 * The main process cannot read a .env file once it is inside an installer, so
 * the values are baked in at build time. A desktop client's secret is not
 * confidential — Google publishes that fact, and PKCE is what actually
 * protects the exchange — but it still should not sit in version control,
 * which is why this file is generated rather than written by hand.
 */
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const env = {};
try {
  for (const line of fs.readFileSync(path.join(root, '.env'), 'utf8').split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) env[m[1]] = m[2].trim();
  }
} catch {
  /* no .env — the app simply will not offer Google in the desktop build */
}

const id = env.KIRUKALS_GOOGLE_DESKTOP_CLIENT_ID || '';
const secret = env.KIRUKALS_GOOGLE_DESKTOP_CLIENT_SECRET || '';

fs.writeFileSync(
  path.join(root, 'electron', 'google-config.cjs'),
  `// Generated by scripts/google-config.cjs — do not edit, do not commit.\n` +
    `module.exports = ${JSON.stringify({ clientId: id, clientSecret: secret }, null, 2)};\n`,
);

console.log(
  id
    ? `  desktop Google client: ${id.slice(0, 24)}…`
    : '  desktop Google client: not set — the installed app will not offer Google',
);
